Assert vs raise Exception

example1
assert cond, "comment"
when cond is False, it would print comment
this is expanded to something like

if cond == False: 
    raise AssertionError("comment")

example2
x = 15
assert x > 10, ‘comment’ 
x = 15 so x > 10 is True, it doesn't print comment
this is expanded to something like

x = 15
if x <= 10:
    raise ValueError('x should not be less than 10')
